# Generated by Django 6.0.7 on 2026-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='enhanced_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='enhanced_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='original_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='original_score',
            field=models.FloatField(default=0.0),
        ),
    ]
